CREATE TABLE pull_requests (
    id TEXT PRIMARY KEY,
    repository_id TEXT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    number INTEGER NOT NULL CHECK (number > 0),
    url TEXT NOT NULL,
    title TEXT NOT NULL,
    author_login TEXT NOT NULL,
    tracked_by TEXT NOT NULL CHECK (tracked_by IN ('forge','user')),
    state TEXT NOT NULL CHECK (state IN ('open','merged','closed')),
    draft INTEGER NOT NULL CHECK (draft IN (0,1)),
    head_branch TEXT NOT NULL,
    head_sha TEXT NOT NULL,
    head_repo TEXT,
    base_branch TEXT NOT NULL,
    checks TEXT NOT NULL CHECK (checks IN ('pending','success','failure','none')),
    review_decision TEXT NOT NULL CHECK (review_decision IN ('approved','changes_requested','review_required','none')),
    unanswered_comments INTEGER NOT NULL CHECK (unanswered_comments >= 0),
    origin_task_id TEXT REFERENCES tasks(id) ON DELETE SET NULL,
    opened_at TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('author','reviewer')),
    ready INTEGER NOT NULL CHECK (ready IN (0,1)),
    last_seen_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (repository_id, number)
);
