import type { PullRequestDto } from "@/api"
export const pull: PullRequestDto = {
  id: "pull-42",
  repository_id: "repo",
  number: 42,
  url: "https://github.com/acme/widgets/pull/42",
  title: "Fix widgets",
  author_login: "someone",
  role: "reviewer",
  tracked_by: "user",
  state: "open",
  draft: false,
  head_branch: "fix",
  head_sha: "abc123",
  head_repo: "https://github.com/me/widgets.git",
  base_branch: "main",
  checks: "pending",
  review_decision: "review_required",
  unanswered_comments: 3,
  failed_checks: [],
  behind_base: false,
  review_asked: false,
  review_requested: true,
  body: "Fixes the widgets that break on an empty list.",
  session_id: null,
  ready: false,
  origin_task_id: null,
  opened_at: "2026-10-01T00:00:00Z",
  last_seen_at: "2026-10-07T00:00:00Z",
  created_at: "2026-10-02T00:00:00Z",
  updated_at: "2026-10-07T01:00:00Z",
}
